# Verwende ein Node.js-Image als Basis
FROM node:18 AS build

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere package.json und package-lock.json (so dass Abhängigkeiten zuerst installiert werden)
COPY package*.json ./

RUN npm cache clean --force

# Installiere Abhängigkeiten
RUN npm install

# Kopiere den gesamten Projektcode
COPY . .

# Baue die React-Anwendung für die Produktion
#RUN npm run build

RUN chmod -R g+rw /app && \
    chmod -R g+rw /app/node_modules && \
    chmod -R g+rw /app/node_modules/.cache

USER 1001
# Exponiere den Port 3000
EXPOSE 3000

# Definiere den Befehl zum Starten der Anwendung
CMD ["npm", "start"]
