# Verwende ein Node.js-Image als Basis
FROM node:18 AS build

# Setze das Arbeitsverzeichnis
WORKDIR /app

# Kopiere package.json und package-lock.json (so dass Abhängigkeiten zuerst installiert werden)
COPY package*.json ./

# Installiere Abhängigkeiten
RUN npm install

# Kopiere den gesamten Projektcode
COPY . .

# Baue die React-Anwendung für die Produktion
#RUN npm run build

# Verwende ein Nginx-Image, um die gebaute Anwendung bereitzustellen
#FROM registry.access.redhat.com/ubi9/nginx-120

# Kopiere die gebaute Anwendung in den Nginx-Server
#COPY --from=build /app/build /usr/share/nginx/html

# Exponiere den Port 3000
EXPOSE 3000

# Definiere den Befehl zum Starten der Anwendung
CMD ["npm", "start"]

# Starte Nginx im Vordergrund
#CMD ["nginx", "-g", "daemon off;"]
