---
#### Cluster Vars
ocp4_version: '4.4.5'
cloud_provider: 'ec2'
cluster_name: 'rcarrata-ocp'
ocp4_base_domain: 'b8a1.sandbox1648.opentlc.com'
aws_region: eu-central-1
master_instance_type: m5.xlarge
master_instance_count: 3
worker_instance_type: m5.xlarge
worker_instance_count: 3
kubeconfig: '~/.kube/ocp4-opentlc2'
machineCIDR: "10.0.0.0/16"
#kubeconfig: "{{ user_path }}/auth/kubeconfig"

#### Only in Tower-mode
tower_used: True
local_kubeconfig: '~/.kube/{{ cluster_name }}'
ocp_cluster: ocpdr

#### Install Vars
awscli-download: False
prereqs: False
uninstall_ocp: False # VERY CAREFUL WITH THIS VAR :)

#### Post Install Vars
only_post_install: False

# Worker Nodes
worker_nodes: False

# Infra Nodes
infra_nodes: False
infra_disk_size: 1024
infra_instance_type: r5.xlarge

# ELK infra nodes
elk_nodes: False

# OAuth
#oauth: htpasswd
oauth: False
ocp4_htpasswd_admin_user: admin
ocp4_htpasswd_dev_user: developer

ocp4_remove_kubeadmin: False
removeselfprovisioning: True

# Logging
logging: True
clo_node_selector: "node-role.kubernetes.io/infra="
es_channel: 4.3 #Define the ES version of the operator
clo_channel: 4.3 #Define the ClusterLogging version of the operator

# Monitoring
monitoring: False
prom_retention: 1w
prometheus_gp2_storage: 40Gi
alertmanager_gp2_storage: 40Gi

# Registry
registry: False

# ProjectRequestTemplate
project_request_template: True
project_request_message: "To provision namespace ask to Openshift 4 Administrators"
install_limit_range: True
install_network_policies: True
install_resource_quota: True
project_request_template_project_limits:
  - type: Container
    max:
      cpu: 2
      memory: 2Gi
    default:
      cpu: 500m
      memory: 500Mi
    defaultRequest:
      cpu: 50m
      memory: 256Mi
  - type: Pod
    max:
      cpu: 2
      memory: 4Gi

project_request_template_resource_quota:
  pods: 10
  requests.cpu: 4000m
  requests.memory: 8Gi
  resourcequotas: 1
  requests.storage: 50Gi
  persistentvolumeclaims: 5

### Extra DevOps Or RH Tools

# ArgoCD
argocd: False
argoclient: False
argocd_version: v1.6.0

# ServiceMesh
service_mesh: False
